services:
  - type: web
    name: api-gateway
    env: docker
    plan: free
    dockerfilePath: ./main-api-gateway/Dockerfile
    envVars:
      - file: ./main-api-gateway/.env
    containerPort: 8000
    hostPort: 8000

  - type: web
    name: authentication-service
    env: docker
    plan: free
    dockerfilePath: ./authentication-service/Dockerfile
    envVars:
      - file: ./authentication-service/.env

  - type: web
    name: notification-service
    env: docker
    plan: free
    dockerfilePath: ./notification-service/Dockerfile
    envVars:
      - file: ./notification-service/.env

  - type: web
    name: qrcode-service
    env: docker
    plan: free
    dockerfilePath: ./qrcode-service/Dockerfile
    envVars:
      - file: ./qrcode-service/.env

  - type: web
    name: reservation-service
    env: docker
    plan: free
    dockerfilePath: ./reservation-service/Dockerfile
    envVars:
      - file: ./reservation-service/.env

databases:
  - name: mongodb
    plan: free
    image: mongo:latest
    volumes:
      - path: /data/db
        size: 1GB

  - name: postgres
    plan: free
    properties:
      image: postgres:latest
      envGroups:
        - name: your-environment-group-name
      volumes:
        - path: /var/lib/postgresql/data
          size: 1GB
