version: 1
services:
  - type: web
    name: api-gateway
    runtime: docker
    dockerfilePath: ./main-api-gateway/Dockerfile
    dockerContext: ./main-api-gateway
    envVars:
      - key: ENV_FILE
        value: ./main-api-gateway/.env
    healthCheckPath: /
    ports:
      - 8000:8000
    depends_on:
      - authentication-service
      - notification-service
      - qrcode-service
      - reservation-service

  - type: web
    name: authentication-service
    runtime: docker
    dockerfilePath: ./authentication-service/Dockerfile
    dockerContext: ./authentication-service
    envVars:
      - key: ENV_FILE
        value: ./authentication-service/.env
    depends_on:
      - mongodb

  - type: web
    name: notification-service
    runtime: docker
    dockerfilePath: ./notification-service/Dockerfile
    dockerContext: ./notification-service
    envVars:
      - key: ENV_FILE
        value: ./notification-service/.env

  - type: web
    name: qrcode-service
    runtime: docker
    dockerfilePath: ./qrcode-service/Dockerfile
    dockerContext: ./qrcode-service
    envVars:
      - key: ENV_FILE
        value: ./qrcode-service/.env

  - type: web
    name: reservation-service
    runtime: docker
    dockerfilePath: ./reservation-service/Dockerfile
    dockerContext: ./reservation-service
    envVars:
      - key: ENV_FILE
        value: ./reservation-service/.env
    depends_on:
      - postgres

  - type: redis
    name: mongodb
    plan: starter

databases:
  - name: postgres
    databaseName: reservista
    region: frankfurt
    postgresMajorVersion: 13
    plan: starter
